# Add cinder user to have the same uid on all servers
- id: cinder_user
  type: puppet
  version: 2.1.0
  groups: [primary-controller, controller, cinder]
  requires: ['hiera']
  required_for: ['netconfig']
  parameters:
    puppet_manifest: puppet/manifests/cinder_user.pp
    puppet_modules:  puppet/modules:/etc/puppet/modules
    timeout: 360

# The task modifies hiera data to add new cinder-types
- id: netapp_hiera_override
  type: puppet
  version: 2.1.0
  groups: [primary-controller]
  requires: [hiera]
  required_for: [globals, create-cinder-types]
  parameters:
    puppet_manifest: puppet/manifests/hiera_override.pp
    puppet_modules:  puppet/modules:/etc/puppet/modules
    timeout: 360

# Execute on controllers only if ceph used for volumes.
# For LCM inherit condition from openstack-cinder
# otherwise enabled_backends will be overwritten.
# https://bugs.launchpad.net/puppet-cinder/+bug/1598094
- id: netapp_cinder_controller
  type: puppet
  version: 2.1.0
  groups: [primary-controller, controller]
  requires: [openstack-cinder]
  required_for: [deploy_end]
  condition:
    yaql_exp: >
      $.storage.volumes_ceph and
      changedAny($.cinder_netapp, $.network_scheme, $.cinder, $.network_metadata.vips,
      $.get('cinder_volume_group'), $.storage, $.ceilometer, $.sahara,
      $.rabbit, $.get('region', 'RegionOne'), $.get('use_ssl'),
      ('primary-controller' in $.roles), $.get('proxy_port'),
      $.get('kombu_compression'), $.get('keystone_endpoint'),
      $.get('glance_endpoint'), $.get('glance_api_servers'),
      $.get('use_syslog'), $.get('use_stderr'), $.get('verbose'), $.debug,
      $.network_metadata.nodes.values().where(
        $.node_roles.any($.matches('controller'))).network_roles.select(
          $.get('mgmt/messaging')),
      $.get('amqp_hosts'), $.get('syslog_log_facility_cinder'),
      $.get('cinder_rate_limits'),
      $.configuration.get('cinder_api_paste_ini'), $.configuration.get('cinder'))
  parameters:
    puppet_manifest: puppet/manifests/site.pp
    puppet_modules:  puppet/modules:/etc/puppet/modules
    timeout: 360

# For LCM inherit condition from top-role-cinder
# otherwise enabled_backends will be overwritten.
# https://bugs.launchpad.net/puppet-cinder/+bug/1598094
- id: netapp_cinder
  type: puppet
  version: 2.1.0
  groups: [cinder]
  requires: [top-role-cinder]
  required_for: [deploy_end]
  condition:
    yaql_exp: >
      changedAny($.cinder_netapp, $.cinder, $.get('cinder_volume_group'),
      $.network_metadata.nodes.get(concat("node-", $.uid)).network_roles.get('cinder/iscsi'),
      $.network_metadata.vips, $.debug, $.node_volumes, $.storage, $.rabbit, $.ceilometer,
      $.get('use_stderr'), $.get('use_syslog'), $.get('syslog_log_facility_cinder'),
      $.get('syslog_log_facility_ceph'), $.get('proxy_port'), $.get('kombu_compression'),
      $.get('use_ssl'), $.get('service_endpoint'), $.get('glance_api_servers'),
      $.get('amqp_hosts'),
      $.network_metadata.nodes.values().where(
        $.node_roles.any($.matches('controller'))).network_roles.select(
          $.get('mgmt/messaging')))
  parameters:
    puppet_manifest: puppet/manifests/site.pp
    puppet_modules:  puppet/modules:/etc/puppet/modules
    timeout: 360

- id: netapp_compute
  type: puppet
  version: 2.1.0
  groups: [compute]
  requires: [top-role-compute]
  required_for: [deploy_end]
  condition:
    yaql_exp: "changed($.cinder_netapp)"
  parameters:
    puppet_manifest: puppet/manifests/compute.pp
    puppet_modules:  puppet/modules:/etc/puppet/modules
    timeout: 360

# Fix hot pluggability.
# Override create-cinder-types task with
# additional dependency on "cinder_netapp".
- id: create-cinder-types
  type: puppet
  version: 2.1.0
  groups: [primary-controller]
  requires: [openstack-cinder]
  required_for: [deploy_end]
  condition:
    yaql_exp: "changedAny($.storage, $.cinder_netapp)"
  parameters:
    puppet_manifest: /etc/puppet/modules/openstack_tasks/examples/openstack-cinder/create_cinder_types.pp
    puppet_modules: /etc/puppet/modules
    timeout: 1200

# Disable swift
- id: swift-proxy_storage
  type: puppet
  version: 2.1.0
  groups: [primary-controller, controller]
  required_for: [deploy_end, controller_remaining_tasks]
  requires: [openstack-controller, primary-rabbitmq, rabbitmq, memcached]
  condition:
    yaql_exp: &swift_enabled >
      ((not $.storage.objects_ceph and not $.storage.images_ceph) and
        not $.storage.images_vcenter and not $.cinder_netapp.disable_swift) and
      (changedAny($.network_scheme, $.network_metadata, $.swift,
        $.get('swift_master_role', 'primary-controller'),
        $.get('swift_object_roles'), ('primary-controller' in $.roles),
        $.get('swift_proxy_roles'), $.get('memcached_addresses'),
        $.network_metadata.nodes.values().where(
          ('controller' in $.node_roles) or
          ('primary-controller' in $.node_roles)),
        $.get('proxy_port'), $.storage, $.debug, $.get('verbose'),
        $.get('swift_ring_min_part_hours'), $.get('deploy_swift_proxy'),
        $.get('use_ssl'), $.rabbit,
        $.network_metadata.nodes.values().where(
          $.node_roles.any($.matches('controller'))).network_roles.select(
            $.get('mgmt/messaging')), $.get('amqp_hosts'),
        $.get('memcache_server_port'), $.ceilometer.enabled, $.mp,
        $.get('swift_partition'), $.get('deploy_swift_storage')))
  cross-depends:
    - name: /(primary-)?rabbitmq/
      role: self
    - name: /glance/
      role: self
    - name: swift-keystone
    - name: memcached
      role: self
    - name: /(primary-)?swift-proxy/
      role: primary-controller
    - name: ceilometer-controller
      role: self
  parameters:
    puppet_manifest: /etc/puppet/modules/openstack_tasks/examples/swift/proxy_storage.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600
  test_pre:
    cmd: ruby /etc/puppet/modules/openstack_tasks/examples/swift/swift_pre.rb
  test_post:
    cmd: ruby /etc/puppet/modules/openstack_tasks/examples/swift/swift_post.rb

- id: swift-rebalance-cron
  type: puppet
  version: 2.1.0
  groups: [primary-controller, controller]
  required_for: [deploy_end]
  requires: [swift-proxy_storage]
  condition:
    yaql_exp: >
      ((not $.storage.objects_ceph and not $.storage.images_ceph) and
        not $.storage.images_vcenter and not $.cinder_netapp.disable_swift) and
      (changedAny($.storage, $.get('swift_master_role', 'primary-controller'),
        $.get('swift_ring_min_part_hours'),('primary-controller' in $.roles)))
  cross-depends:
    - name: /(primary-)?swift-proxy/
      role: self
  parameters:
    puppet_manifest: /etc/puppet/modules/openstack_tasks/examples/swift/rebalance_cronjob.pp
    puppet_modules: /etc/puppet/modules
    timeout: 300
  test_pre:
    cmd: ruby /etc/puppet/modules/openstack_tasks/examples/swift/swift_post.rb
  test_post:
    cmd: ruby /etc/puppet/modules/openstack_tasks/examples/swift/rebalance_cronjob_post.rb

- id: swift-keystone
  type: puppet
  version: 2.1.0
  groups: [primary-controller]
  required_for: [swift-proxy_storage]
  condition:
    yaql_exp: >
      ((not $.storage.objects_ceph and not $.storage.images_ceph) and
        not $.storage.images_vcenter and not $.cinder_netapp.disable_swift) and
      (changedAny($.swift, $.network_metadata.vips,
        $.get('region', 'RegionOne'), $.public_ssl, $.get('use_ssl')))
  cross-depends:
    - name: keystone
      role: self
  requires: [primary-keystone, keystone]
  parameters:
    puppet_manifest: /etc/puppet/modules/openstack_tasks/examples/swift/keystone.pp
    puppet_modules: /etc/puppet/modules
    timeout: 1800

- id: openstack-haproxy-swift
  type: puppet
  version: 2.1.0
  groups: [primary-controller, controller]
  required_for: [deploy_end]
  requires: [deploy_start, primary-cluster-haproxy, cluster-haproxy]
  condition:
    yaql_exp: >
      changedAny($.storage, $.get('swift_proxy_roles'),
      $.network_metadata.nodes.values().where(
        ('controller' in $.node_roles) or
        ('primary-controller' in $.node_roles)),
      $.public_ssl, $.get('use_ssl'), $.get('external_lb'),
      $.get('swift_server_names'), $.get('swift_ipaddresses'),
      $.network_metadata.vips, $.ironic, $.network_scheme,
      $.network_metadata.nodes.get(concat('node-', $.uid))) and not $.cinder_netapp.disable_swift
  cross-depends:
    - name: /(primary-)?cluster-haproxy/
      role: self
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/openstack-haproxy/openstack-haproxy-swift.pp
    puppet_modules: /etc/puppet/modules
    timeout: 300
  test_pre:
    cmd: ruby /etc/puppet/modules/osnailyfacter/modular/openstack-haproxy/openstack-haproxy_pre.rb
  test_post:
    cmd: ruby /etc/puppet/modules/osnailyfacter/modular/openstack-haproxy/openstack-haproxy-swift_post.rb
